### ISSUE TITLE
Suggestions for the repo title?

### ISSUE THREAD

**Issue by LuckyMD** [theislab/Covid_meta_analysis#1]
@LisaSikkema @gokceneraslan do you have any suggestions for the title of the repo to me more encompassing for all analyses that were done? Maybe sth around:
- Covid_sc_screening_meta_analysis

What would you call the module analysis, the cross-tissue double positive cell screens as a collective?

**Comment by LisaSikkema** [comment]
yes I think something like covid_sc_meta_analysis, or covid_entry_factor_sc_meta_analysis, although that's a bit long

**Comment by LuckyMD** [comment]
covid_entry_factor_analysis ?

**Comment by LisaSikkema** [comment]
I think we should include "meta", that's an important characteristic of the analysis... is covid_entry_factor_meta_analysis too long, you think?

**Comment by LuckyMD** [comment]
Maybe yes... You could say meta analysis is a subset of the entry factor analysis, no? Any other opinions, @gokceneraslan ?

**Comment by LisaSikkema** [comment]
I think we call the whole thing meta-analysis, also in the title of the paper
